-- Script to drop created tables

DROP TABLE Staff;
DROP TABLE Taxi CASCADE CONSTRAINTS;
DROP TABLE Business CASCADE CONSTRAINTS;
DROP TABLE Contract CASCADE CONSTRAINTS;
DROP TABLE Office CASCADE CONSTRAINTS;
DROP TABLE Assignment CASCADE CONSTRAINTS;
DROP TABLE Job CASCADE CONSTRAINTS;
DROP Table Private CASCADE CONSTRAINTS;
